PREFIX ag: <http://example.org/agent#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?action ?label ?file
WHERE {
  ?action a ag:Action ;
          rdfs:label ?label ;
          prov:used ?file .
}
